springfox:
  documentation:
    swagger-ui:
      enabled: ${swagger.enable:false}


swagger:
  enable: true
  base-package: org.bougainvillea.spring
  path-regex: /error.*
  title: Global interface
  description: Global interface
  version: 0.0.3
  service-url: http://localhost
  license: MIT
  license-url: https://github.com/caddyRen/spring/blob/develop-2.0x/LICENSE
  name: 希君生羽翼 一化北溟鱼
  url: https://bougainvilleas.github.io/lotus/
  email: caddyren@qq.com
